repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: detect-private-key
  - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.82.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-write=false

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
    - id: shellcheck
      args: ["--enable require-variable-braces,deprecate-which"]